var ytcfg={d:function(){return window.yt&amp;&amp;yt.config_||ytcfg.data_||(ytcfg.data_={})},get:function(k,o){
    return k in ytcfg.d()?ytcfg.d()[k]:o},
    set:function(){var a=arguments;if(a.length&gt;1)ytcfg.d()[a[0]]=a[1];
        else for(var k in a[0])ytcfg.d()[k]=a[0][k]}};
ytcfg.set({"EVENT_ID":"TmI8ZNTRBdO25gSXqI_YBQ","EXPERIMENT_FLAGS":
{"H5_enable_full_pacf_logging":true,"H5_use_async_logging":true,"allow_skip_networkless":true,"always_send_and_write":true,
"autoescape_tempdata_url":true,"background_thread_flush_logs_due_to_batch_limit":true,"cancel_pending_navs":true,
"clear_user_partitioned_ls":true,"csi_on_gel":true,"deprecate_csi_has_info":true,"deprecate_pair_servlet_enabled":true,
"deprecate_two_way_binding_child":true,"deprecate_two_way_binding_parent":true,"desktop_client_release":true,
"desktop_image_cta_no_background":true,"desktop_log_img_click_location":true,"desktop_notification_high_priority_ignore_push":true,
"desktop_notification_set_title_bar":true,"desktop_sparkles_light_cta_button":true,"disable_child_node_auto_formatted_strings":true,
"disable_pacf_logging_for_memory_limited_tv":true,"disable_simple_mixed_direction_formatted_strings":true,"disable_thumbnail_preloading":true,
"embeds_web_enable_replace_unload_w_pagehide":true,"embeds_web_enable_ve_logging_unification":true,"embeds_web_nwl_disable_nocookie":true,
"enable_docked_chat_messages":true,"enable_h5_instream_watch_next_params_oarlib":true,"enable_h5_video_ads_oarlib":true,"enable_handles_account_menu_switcher":true,
"enable_mixed_direction_formatted_strings":true,"enable_rejected_sasde_for_html5":true,"enable_skip_ad_guidance_prompt":true,"enable_skippable_ads_for_unplugged_ad_pod":true,
"enable_smearing_expansion_dai":true,"enable_third_party_info":true,"enable_watch_next_pause_autoplay_lact":true,"enable_ypc_spinners":true,
"enable_yt_ata_iframe_authuser":true,"export_networkless_options":true,"fill_single_video_with_notify_to_lasr":true,
"gfeedback_for_signed_out_users_enabled":true,"gpa_sparkles_ten_percent_layer":true,"h5_companion_enable_adcpn_macro_substitution_for_click_pings":true,
"h5_enable_generic_error_logging_event":true,"h5_inplayer_enable_adcpn_macro_substitution_for_click_pings":true,
"hide_endpoint_overflow_on_ytd_display_ad_renderer":true,"html5_enable_ads_client_monitoring_log_tv":true,"html5_enable_single_video_vod_ivar_on_pacf":true,
"html5_log_trigger_events_with_debug_data":true,"html5_web_enable_halftime_preroll":true,"il_use_view_model_logging_context":true,"json_condensed_response":true,
"kevlar_dropdown_fix":true,"kevlar_gel_error_routing":true,"kevlar_guide_refresh":true,"kevlar_set_sd_enabled_browse_request":true,"kevlar_undo_delete":true,
"live_chat_increased_min_height":true,"log_errors_through_nwl_on_retry":true,"log_vis_on_tab_change":true,
"log_web_endpoint_to_layer":true,"mdx_enable_privacy_disclosure_ui":true,"mdx_load_cast_api_bootstrap_script":true,
"migrate_events_to_ts":true,"networkless_logging":true,"no_sub_count_on_sub_button":true,"nwl_send_from_memory_when_online":true,
"pageid_as_header_web":true,"polymer_bad_build_labels":true,"polymer_verifiy_app_state":true,"qoe_send_and_write":true,
"scheduler_use_raf_by_default":true,"service_worker_enabled":true,"service_worker_push_enabled":true,"service_worker_push_home_page_prompt":true,
"service_worker_push_watch_page_prompt":true,"shorten_initial_gel_batch_timeout":true,"skip_invalid_ytcsi_ticks":true,"skip_setting_info_in_csi_data_object":true,
"super_sticker_emoji_picker_category_button_icon_filled":true,"suppress_error_204_logging":true,"transport_use_scheduler":true,"use_new_cml":true,
"use_new_in_memory_storage":true,"use_new_nwl_initialization":true,"use_new_nwl_saw":true,"use_new_nwl_stw":true,"use_new_nwl_wts":true,"use_player_abuse_bg_library":true,
"use_request_time_ms_header":true,"use_session_based_sampling":true,"use_ts_visibilitylogger":true,"use_watch_fragments2":true,"verify_ads_itag_early":true,"vss_final_ping_send_and_write":true,
"vss_playback_use_send_and_write":true,"warm_load_nav_start_web":true,"web_always_load_chat_support":true,"web_api_url":true,"web_dedupe_ve_grafting":true,
"web_enable_error_204":true,"web_enable_voz_audio_feedback":true,"web_gel_timeout_cap":true,"web_one_platform_error_handling":true,"web_prefetch_preload_video":true,
"web_yt_config_context":true,"ytidb_clear_embedded_player":true,"H5_async_logging_delay_ms":30000.0,"addto_ajax_log_warning_fraction":0.1,
"autoplay_pause_by_lact_sampling_fraction":0.0,"log_window_onerror_fraction":0.1,"tv_pacf_logging_sample_rate":0.01,"web_system_health_fraction":0.01,
"ytidb_transaction_ended_event_rate_limit":0.02,"ytidb_transaction_ended_event_rate_limit_session":0.2,"ytidb_transaction_ended_event_rate_limit_transaction":0.1,
"autoplay_pause_by_lact_sec":0,"botguard_async_snapshot_timeout_ms":3000,"check_navigator_accuracy_timeout_ms":0,"compression_disable_point":10,
"compression_performance_threshold":250,"gel_queue_timeout_max_ms":60000,"initial_gel_batch_timeout":2000,"log_web_meta_interval_ms":0,
"max_prefetch_window_sec_for_livestream_optimization":10,"min_prefetch_offset_sec_for_livestream_optimization":20,"network_polling_interval":30000,
"pacf_logging_delay_milliseconds_through_ybfe_tv":0,"polymer_log_prop_change_observer_percent":0,"prefetch_comments_ms_after_video":0,"send_config_hash_timer":0,
"service_worker_push_logged_out_prompt_watches":-1,"service_worker_push_prompt_cap":-1,"service_worker_push_prompt_delay_microseconds":3888000000000,
"slow_compressions_before_abandon_count":4,"watch_next_pause_autoplay_lact_sec":4500,"web_foreground_heartbeat_interval_ms":28000,"web_gel_debounce_ms":10000,
"web_logging_max_batch":100,"web_smoothness_test_duration_ms":0,"web_smoothness_test_method":0,"ytidb_remake_db_retries":3,"ytidb_reopen_db_retries":3,
"embeds_web_synth_ch_headers_banned_urls_regex":"","live_chat_unicode_emoji_json_url":"https://www.gstatic.com/youtube/img/emojis/emojis-svg-9.json",
"service_worker_push_force_notification_prompt_tag":"1","service_worker_scope":"/","web_client_version_override":"","kevlar_command_handler_command_banlist":[],
"web_op_signal_type_banlist":[]},"GAPI_HINT_PARAMS":"m;/_/scs/abc-static/_/js/k\u003dgapi.gapi.en.fpEXMBCWMKc.O/d\u003d1/rs\u003dAHpOoo9SQGHwxhl93I-W5KEIEdf87vGuqQ/m\u003d__features__",
"GAPI_HOST":"https://apis.google.com","GAPI_LOCALE":"pt_BR","GL":"BR","HL":"pt","HTML_LANG":"pt-BR","INNERTUBE_API_KEY":"AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
"INNERTUBE_API_VERSION":"v1","INNERTUBE_CLIENT_NAME":"WEB_EMBEDDED_PLAYER","INNERTUBE_CLIENT_VERSION":"1.20230411.01.00","INNERTUBE_CONTEXT":{"client":{"hl":"pt","gl":"BR","remoteHost":"179.34.78.43",
"deviceMake":"Google","deviceModel":"Nexus 5","visitorData":"CgtvMWxHaXAtc0NUcyjOxPGhBg%3D%3D","userAgent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36,gzip(gfe)",
"clientName":"WEB_EMBEDDED_PLAYER","clientVersion":"1.20230411.01.00","osName":"Android","osVersion":"6.0",
"originalUrl":"https://www.youtube.com/embed/no7ww_BP2xo?feature\u003doembed\u0026autoplay\u003d1\u0026color\u0026autopause\u003d0\u0026loop\u003d0\u0026muted\u003d0\u0026title\u003d0\u0026portrait\u003d0\u0026byline\u003d0",
"screenPixelDensity":2,"platform":"MOBILE","clientFormFactor":"UNKNOWN_FORM_FACTOR","configInfo":{"appInstallData":"CM7E8aEGEKC3_hIQt5GvBRDX_64FEOSz_hIQvbauBRDW7q4FEOWg_hIQzK7-EhC4i64FEIv5rgUQ5_euBRDthq8FEIWDrwUQzN-uBQ%3D%3D"},
"screenDensityFloat":2.0,"browserName":"Chrome Mobile","browserVersion":"112.0.0.0","acceptHeader":"text/html,application/xhtml+xml,application/xml;q\u003d0.9,image/avif,image/webp,image/apng,*/*;
q\u003d0.8,application/signed-exchange;v\u003db3;q\u003d0.7","deviceExperimentId":"ChxOekU0TnpreU1UTTFOell5TURrek1UUXhPUT09EM7E8aEGGOTAgp4G"},"user":{"lockedSafetyMode":false},
"request":{"useSsl":true},"clickTracking":{"clickTrackingParams":"IhMI1LCQmKav/gIVU5uZCh0X1ANbMgZvZW1iZWQ\u003d"}},
"INNERTUBE_CONTEXT_CLIENT_NAME":56,"INNERTUBE_CONTEXT_CLIENT_VERSION":"1.20230411.01.00","INNERTUBE_CONTEXT_GL":"BR","INNERTUBE_CONTEXT_HL":"pt",
"LATEST_ECATCHER_SERVICE_TRACKING_PARAMS":{"client.name":"WEB_EMBEDDED_PLAYER"},"SERVER_NAME":"WebFE","SESSION_INDEX":"0","VISITOR_DATA":"CgtvMWxHaXAtc0NUcyjOxPGhBg%3D%3D",
"WEB_PLAYER_CONTEXT_CONFIGS":{"WEB_PLAYER_CONTEXT_CONFIG_ID_EMBEDDED_PLAYER":{"rootElementId":"movie_player","jsUrl":"/s/player/36754c51/player_ias.vflset/pt_BR/base.js","cssUrl":"/s/player/36754c51/www-player.css",
"contextId":"WEB_PLAYER_CONTEXT_CONFIG_ID_EMBEDDED_PLAYER","eventLabel":"embedded","contentRegion":"BR","hl":"pt_BR","hostLanguage":"pt","playerStyle":"native","innertubeApiKey":"AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8",
"innertubeApiVersion":"v1","innertubeContextClientVersion":"1.20230411.01.00","device":{"brand":"google","model":"nexus 5","browser":"Chrome Mobile",
"browserVersion":"112.0.0.0","os":"Android","osVersion":"6.0","platform":"MOBILE","interfaceName":"WEB_EMBEDDED_PLAYER","interfaceVersion":"1.20230411.01.00","deviceYear":2014},
"serializedExperimentIds":"23848211,23983296,24004644,24007246,24080738,24135310,24169501,24255163,24415864,24439361,24450367,24468691,24474986,24482081,24499792,24516157,24534937,24539776,39323074",
"serializedExperimentFlags":"H5_async_logging_delay_ms\u003d30000.0\u0026H5_enable_full_pacf_logging\u003dtrue\u0026H5_use_async_logging\u003dtrue\u0026ad_pod_disable_companion_persist_ads_quality\
u003dtrue\u0026addto_ajax_log_warning_fraction\u003d0.1\u0026align_ad_to_video_player_lifecycle_for_bulleit\u003dtrue\u0026allow_live_autoplay\u003dtrue\u0026allow_poltergust_autoplay\u003dtrue\u0026allow_skip_networkless\
u003dtrue\u0026always_send_and_write\u003dtrue\u0026autoplay_time\u003d10000\u0026autoplay_time_for_fullscreen\u003d-1\u0026autoplay_time_for_music_content\u003d-1\u0026background_thread_flush_logs_due_to_batch_limit\u003dtrue\
u0026bg_vm_reinit_threshold\u003d7200000\u0026blocked_packages_for_sps\u003d[]\u0026botguard_async_snapshot_timeout_ms\u003d3000\u0026check_ad_ui_status_for_mweb_sa…